name = "PanelCutting"
uuid = "c1372bff-64f3-4c29-a5fb-167619e966f3"
version = "0.1.0"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]

[deps]
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
NahaXMLUtils = "a43006d0-e7b0-4945-abab-c94506b32220"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PropertyMethods = "347c79ec-5835-41b8-b087-11d269c34aff"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulUS = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[sources]
NahaXMLUtils = {url = "https://github.com/MarkNahabedian/NahaXMLUtils.jl"}

[compat]
Cascadia = "1.0.2"
DataStructures = "0.18"
DisplayAs = "0.1"
Gumbo = "0.8.3"
JSON = "1.2.0"
Match = "1"
NahaXMLUtils = "1.0.0"
Plots = "1"
StructUtils = "2.5.1"
URIs = "1.6.1"
Unitful = "1.9"
UnitfulUS = "0.1, 0.2"
XML = "0.3.2"
julia = "1.12"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulUS = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"

[targets]
test = ["InteractiveUtils", "Test", "Unitful", "UnitfulUS"]
